### ISSUE TITLE
Confirm that everyone accepts the policies

### ISSUE THREAD

**Issue by micahlt** [Scratch-Client-4/contributing#1]
I know most of the collaborators very well, but I want everyone to confirm that they accept the policies before this issue is closed.  I appreciate it!  :D

**Comment by Ekmand** [comment]
I accept it bud xD

**Comment by ethanhanderson** [comment]
I'm fine with those rules. :)

**Comment by icarusinthewings** [comment]
I agree with these. If these rules are broken, are they kicked from the project? Also, does bad words include like hinting at it?

**Comment by icarusinthewings** [comment]
Wait... I didn't unassign anyone!

**Comment by micahlt** [comment]
@ConvexPolygon The idea is, follow the rules.  If you don't we'll probably give you a warning first, and then maybe kick you.

**Comment by retronbv** [comment]
@micahlt add me plz i help

**Comment by micahlt** [comment]
@YOYITsM3M8 I think we've got most of the help we need with the team right now, but feel free to submit a pull request!

**Comment by retronbv** [comment]
:D ok

**Comment by retronbv** [comment]
> @YOYITsM3M8 I think we've got most of the help we need with the team right now, but feel free to submit a pull request!

just saying this is what i am doing rn i think it looks good bc i am basing off of ekmand's project
https://scratch-redesign--retronbv.repl.co/

**Comment by micahlt** [comment]
That does look cool, but Ekmand built his project in Figma which actually generates CSS, so we're going to build on that.

**Comment by ethanhanderson** [comment]
> > @YOYITsM3M8 I think we've got most of the help we need with the team right now, but feel free to submit a pull request!
> 
> 
> 
> just saying this is what i am doing rn i think it looks good bc i am basing off of ekmand's project
> 
> https://scratch-redesign--retronbv.repl.co/

Feel free to make it on your own, but we’re gonna make this based on the real design

**Comment by retronbv** [comment]
thats fine!

**Comment by arwen-undomiel** [comment]
Hey, I just joined, My name's Maia. I accept the policies. You'll see me around soon. Just getting a hang of the code and such.

**Comment by micahlt** [comment]
Cool!  Welcome to the team!

**Comment by moeenio** [comment]
I accept these :P

**Comment by VFDan** [comment]
I accept these policies :) (Woah, I know almost everyone here o_O)

**Comment by micahlt** [comment]
@Scratch-Client-4/everyone All right!  Looks like that's everyone!  Currently there's not a lot to work on because Hexsphere, Ekmand, and I are still working on perfecting the design aspect of things before we go into the development stage.

**Comment by moeenio** [comment]
> @Scratch-Client-4/everyone All right! Looks like that's everyone! Currently there's not a lot to work on because Hexsphere, Ekmand, and I are still working on perfecting the design aspect of things before we go into the development stage.

Alright. I gladly want to help make the design into code ;)

**Comment by meatIoaf** [comment]
I accept! (Hello, [Aurax](https://scratch.mit.edu/users/Aurax) here!)

**Comment by moeenio** [comment]
@micahlt I'm not sure I should have the right to manage issues and PRs tho (I can)

**Comment by micahlt** [comment]
@locness3 I feel comfortable with you managing it- you're probably more advanced at what we're doing than I am.

**Comment by moeenio** [comment]
Oh, thanks

**Comment by forevertooo** [comment]
Hi there ! I am haydenledean on Scratch from the Codec Team ! Can i join the project to make the engine ? I know some Node.JS and i know HTML some JS and CSS ! Thanks ! - haydenledean

**Comment by moeenio** [comment]
I'm not sure what "engine" you mean. The current focus of SC4 is to create a client to access the Scratch community, not to reinvent the Scratch editor.

**Comment by forevertooo** [comment]
Yeah i know. I really want to help... Can i ?

**Comment by moeenio** [comment]
@micahlt @Ekmand

**Comment by forevertooo** [comment]
?

**Comment by moeenio** [comment]
I'm pinging them, so they see you want to join

**Comment by micahlt** [comment]
Ah, sorry.  Yeah, I'll add you.

**Comment by forevertooo** [comment]
So... Then i accept ! I will start to code but... where send it to be aprouved ?

**Comment by moeenio** [comment]
Are you comfortable with Git and npm? You will need both to contribute code. If yes, you can make your changes on a branch, and make pull requests to submit them.

**Comment by forevertooo** [comment]
I use NPM with Node.JS for build and install things. I will do this. But the request i do will be added now or first analysed ?

**Comment by forevertooo** [comment]
AND i am not in a team.

**Comment by moeenio** [comment]
> But the request i do will be added now or first analysed

We'll review your changes first, obviously ;)

> AND i am not in a team.

Ask an admin to put you in one.

**Comment by forevertooo** [comment]
Sorry but where ?

**Comment by moeenio** [comment]
Where would you like to be? @Ekmand Can you add him there?

**Comment by forevertooo** [comment]
Hmmm... Maybe Everyone first. maybe Design i like drawing and i really like coding then Backend

**Comment by moeenio** [comment]
You like drawing, but are you comfortable with design software (here Figma) and UI design?

For now please add him to everyone (he should already have been btw).

**Comment by forevertooo** [comment]
Hmmm not really so no... Only coding. Then Backend ?

**Comment by moeenio** [comment]
I guess yes, if you know NodeJS. Please add him to Everyone (he should already be here tho) and Backend @micahlt @Ekmand

**Comment by githubfan** [comment]
Hey, I'm joshuay2 on scratch and would like to join. I do accept the policies if I am accepted. I know HTML, CSS, JS, Node JS and I use figma regularly.

**Comment by moeenio** [comment]
if you join, you should learn VUE and LESS.

**Comment by githubfan** [comment]
Alright, thats cool.

**Comment by forevertooo** [comment]
@micahlt @Ekmand Can i be in everyone ?
