### ISSUE TITLE
Welcome messages

### ISSUE THREAD

**Issue by micahlt** [Scratch-Client-4/contributing#2]
Everyone, please welcome @YOYITsM3M8 and @4meltdown4 to the Scratch Client 4 team!  :tada: They will both be working on the frontend side of things.

**Comment by icarusinthewings** [comment]
Yay -- Wait, we have to many frontend workers!

**Comment by icarusinthewings** [comment]
I promise you, I never unassigned smiley! it automatically did it!

**Comment by micahlt** [comment]
That's weird... And you can never have too many workers!  Also, @Scratch-Client-4/frontend make sure you're familiar with the [stack plan](https://github.com/Scratch-Client-4/client/issues/1) before you work on the client itself.
